class AsmaUlHusnaModel {
  final int number;
  final String arabic;
  final String transliteration;
  final String meaning;
  final String urduMeaning;

  const AsmaUlHusnaModel({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.meaning,
    required this.urduMeaning,
  });
}

/// Core V1 dataset for the Asma ul Husna experience.
/// Keep this list local so the feature works offline.
const List<AsmaUlHusnaModel> asmaUlHusna = [
  AsmaUlHusnaModel(number: 1, arabic: 'اللّٰه', transliteration: 'ALLAH', meaning: 'The One worthy of worship', urduMeaning: 'معبودِ برحق'),
  AsmaUlHusnaModel(number: 2, arabic: 'الرَّحْمٰنُ', transliteration: 'AR-RAHMAAN', meaning: 'The Most Merciful', urduMeaning: 'نہایت رحم فرمانے والا'),
  AsmaUlHusnaModel(number: 3, arabic: 'الرَّحِيمُ', transliteration: 'AR-RAHEEM', meaning: 'The Especially Merciful', urduMeaning: 'بہت رحم کرنے والا'),
  AsmaUlHusnaModel(number: 4, arabic: 'الْمَلِكُ', transliteration: 'AL-MALIK', meaning: 'The King, the Sovereign', urduMeaning: 'بادشاہ، حقیقی مالک'),
  AsmaUlHusnaModel(number: 5, arabic: 'الْقُدُّوسُ', transliteration: 'AL-QUDDOOS', meaning: 'The Absolutely Pure', urduMeaning: 'نہایت پاک'),
  AsmaUlHusnaModel(number: 6, arabic: 'السَّلَامُ', transliteration: 'AS-SALAAM', meaning: 'The Source of Peace and Perfection', urduMeaning: 'سلامتی دینے والا'),
  AsmaUlHusnaModel(number: 7, arabic: 'الْمُؤْمِنُ', transliteration: 'AL-MU’MIN', meaning: 'The Giver of Security', urduMeaning: 'امن دینے والا'),
  AsmaUlHusnaModel(number: 8, arabic: 'الْمُهَيْمِنُ', transliteration: 'AL-MUHAYMIN', meaning: 'The Guardian', urduMeaning: 'نگہبان'),
  AsmaUlHusnaModel(number: 9, arabic: 'الْعَزِيزُ', transliteration: 'AL-AZEEZ', meaning: 'The Almighty', urduMeaning: 'زبردست، غالب'),
  AsmaUlHusnaModel(number: 10, arabic: 'الْجَبَّارُ', transliteration: 'AL-JABBAAR', meaning: 'The Compeller, the Restorer', urduMeaning: 'زبردست اقتدار والا'),
  AsmaUlHusnaModel(number: 11, arabic: 'الْمُتَكَبِّرُ', transliteration: 'AL-MUTAKABBIR', meaning: 'The Supreme', urduMeaning: 'بڑائی والا'),
  AsmaUlHusnaModel(number: 12, arabic: 'الْخَالِقُ', transliteration: 'AL-KHAALIQ', meaning: 'The Creator', urduMeaning: 'پیدا کرنے والا'),
  AsmaUlHusnaModel(number: 13, arabic: 'الْبَارِئُ', transliteration: 'AL-BAARI', meaning: 'The Originator', urduMeaning: 'وجود میں لانے والا'),
  AsmaUlHusnaModel(number: 14, arabic: 'الْمُصَوِّرُ', transliteration: 'AL-MUSAWWIR', meaning: 'The Fashioner', urduMeaning: 'صورت بنانے والا'),
  AsmaUlHusnaModel(number: 15, arabic: 'الْغَفَّارُ', transliteration: 'AL-GHAFFAAR', meaning: 'The Constantly Forgiving', urduMeaning: 'بہت بخشنے والا'),
  AsmaUlHusnaModel(number: 16, arabic: 'الْقَهَّارُ', transliteration: 'AL-QAHHAAR', meaning: 'The All-Subduing', urduMeaning: 'سب پر غالب'),
  AsmaUlHusnaModel(number: 17, arabic: 'الْوَهَّابُ', transliteration: 'AL-WAHHAAB', meaning: 'The Bestower', urduMeaning: 'بہت عطا کرنے والا'),
  AsmaUlHusnaModel(number: 18, arabic: 'الرَّزَّاقُ', transliteration: 'AR-RAZZAAQ', meaning: 'The Provider', urduMeaning: 'رزق دینے والا'),
  AsmaUlHusnaModel(number: 19, arabic: 'الْفَتَّاحُ', transliteration: 'AL-FATTAAH', meaning: 'The Opener', urduMeaning: 'راستے کھولنے والا'),
  AsmaUlHusnaModel(number: 20, arabic: 'الْعَلِيمُ', transliteration: 'AL-‘ALEEM', meaning: 'The All-Knowing', urduMeaning: 'سب کچھ جاننے والا'),
  AsmaUlHusnaModel(number: 21, arabic: 'الْقَابِضُ', transliteration: 'AL-QAABID', meaning: 'The Withholder', urduMeaning: 'روکنے والا'),
  AsmaUlHusnaModel(number: 22, arabic: 'الْبَاسِطُ', transliteration: 'AL-BAASIT', meaning: 'The Expander', urduMeaning: 'کشادگی دینے والا'),
  AsmaUlHusnaModel(number: 23, arabic: 'الْخَافِضُ', transliteration: 'AL-KHAAFID', meaning: 'The One who Lowers', urduMeaning: 'پست کرنے والا'),
  AsmaUlHusnaModel(number: 24, arabic: 'الرَّافِعُ', transliteration: 'AR-RAAFI', meaning: 'The Exalter', urduMeaning: 'بلند کرنے والا'),
  AsmaUlHusnaModel(number: 25, arabic: 'الْمُعِزُّ', transliteration: 'AL-MU‘IZZ', meaning: 'The Giver of Honour', urduMeaning: 'عزت دینے والا'),
  AsmaUlHusnaModel(number: 26, arabic: 'الْمُذِلُّ', transliteration: 'AL-MUDHILL', meaning: 'The Humiliator', urduMeaning: 'ذلت دینے والا'),
  AsmaUlHusnaModel(number: 27, arabic: 'السَّمِيعُ', transliteration: 'AS-SAMEE‘', meaning: 'The All-Hearing', urduMeaning: 'سب کچھ سننے والا'),
  AsmaUlHusnaModel(number: 28, arabic: 'الْبَصِيرُ', transliteration: 'AL-BASEER', meaning: 'The All-Seeing', urduMeaning: 'سب کچھ دیکھنے والا'),
  AsmaUlHusnaModel(number: 29, arabic: 'الْحَكَمُ', transliteration: 'AL-HAKAM', meaning: 'The Judge', urduMeaning: 'فیصلہ کرنے والا'),
  AsmaUlHusnaModel(number: 30, arabic: 'الْعَدْلُ', transliteration: 'AL-‘ADL', meaning: 'The Utterly Just', urduMeaning: 'نہایت انصاف والا'),
  AsmaUlHusnaModel(number: 31, arabic: 'اللَّطِيفُ', transliteration: 'AL-LATEEF', meaning: 'The Subtle and Gentle', urduMeaning: 'نرمی اور لطف فرمانے والا'),
  AsmaUlHusnaModel(number: 32, arabic: 'الْخَبِيرُ', transliteration: 'AL-KHABEER', meaning: 'The All-Aware', urduMeaning: 'باخبر'),
  AsmaUlHusnaModel(number: 33, arabic: 'الْحَلِيمُ', transliteration: 'AL-HALEEM', meaning: 'The Forbearing', urduMeaning: 'بردبار'),
  AsmaUlHusnaModel(number: 34, arabic: 'الْعَظِيمُ', transliteration: 'AL-‘AZEEM', meaning: 'The Magnificent', urduMeaning: 'عظمت والا'),
  AsmaUlHusnaModel(number: 35, arabic: 'الْغَفُورُ', transliteration: 'AL-GHAFOOR', meaning: 'The Great Forgiver', urduMeaning: 'بہت بخشنے والا'),
  AsmaUlHusnaModel(number: 36, arabic: 'الشَّكُورُ', transliteration: 'ASH-SHAKOOR', meaning: 'The Appreciative', urduMeaning: 'قدردان'),
  AsmaUlHusnaModel(number: 37, arabic: 'الْعَلِيُّ', transliteration: 'AL-‘ALIYY', meaning: 'The Most High', urduMeaning: 'سب سے بلند'),
  AsmaUlHusnaModel(number: 38, arabic: 'الْكَبِيرُ', transliteration: 'AL-KABEER', meaning: 'The Most Great', urduMeaning: 'بہت بڑا'),
  AsmaUlHusnaModel(number: 39, arabic: 'الْحَفِيظُ', transliteration: 'AL-HAFEEZ', meaning: 'The Preserver', urduMeaning: 'حفاظت کرنے والا'),
  AsmaUlHusnaModel(number: 40, arabic: 'الْمُقِيتُ', transliteration: 'AL-MUQEET', meaning: 'The Sustainer', urduMeaning: 'قوت اور روزی دینے والا'),
  AsmaUlHusnaModel(number: 41, arabic: 'الْحَسِيبُ', transliteration: 'AL-HASEEB', meaning: 'The Reckoner, the Sufficient', urduMeaning: 'حساب لینے والا، کافی'),
  AsmaUlHusnaModel(number: 42, arabic: 'الْجَلِيلُ', transliteration: 'AL-JALEEL', meaning: 'The Majestic', urduMeaning: 'جلال والا'),
  AsmaUlHusnaModel(number: 43, arabic: 'الْكَرِيمُ', transliteration: 'AL-KAREEM', meaning: 'The Most Generous', urduMeaning: 'بہت کرم کرنے والا'),
  AsmaUlHusnaModel(number: 44, arabic: 'الرَّقِيبُ', transliteration: 'AR-RAQEEB', meaning: 'The Watchful', urduMeaning: 'نگہبان'),
  AsmaUlHusnaModel(number: 45, arabic: 'الْمُجِيبُ', transliteration: 'AL-MUJEEB', meaning: 'The Responsive', urduMeaning: 'دعائیں قبول کرنے والا'),
  AsmaUlHusnaModel(number: 46, arabic: 'الْوَاسِعُ', transliteration: 'AL-WAASI‘', meaning: 'The All-Encompassing', urduMeaning: 'وسعت والا'),
  AsmaUlHusnaModel(number: 47, arabic: 'الْحَكِيمُ', transliteration: 'AL-HAKEEM', meaning: 'The All-Wise', urduMeaning: 'حکمت والا'),
  AsmaUlHusnaModel(number: 48, arabic: 'الْوَدُودُ', transliteration: 'AL-WADOOD', meaning: 'The Most Loving', urduMeaning: 'بہت محبت کرنے والا'),
  AsmaUlHusnaModel(number: 49, arabic: 'الْمَجِيدُ', transliteration: 'AL-MAJEED', meaning: 'The Most Glorious', urduMeaning: 'بزرگی والا'),
  AsmaUlHusnaModel(number: 50, arabic: 'الْبَاعِثُ', transliteration: 'AL-BAA‘ITH', meaning: 'The Resurrector', urduMeaning: 'اٹھانے والا'),
  AsmaUlHusnaModel(number: 51, arabic: 'الشَّهِيدُ', transliteration: 'ASH-SHAHEED', meaning: 'The Witness', urduMeaning: 'گواہ'),
  AsmaUlHusnaModel(number: 52, arabic: 'الْحَقُّ', transliteration: 'AL-HAQQ', meaning: 'The Truth', urduMeaning: 'برحق'),
  AsmaUlHusnaModel(number: 53, arabic: 'الْوَكِيلُ', transliteration: 'AL-WAKEEL', meaning: 'The Trustee', urduMeaning: 'کارساز'),
  AsmaUlHusnaModel(number: 54, arabic: 'الْقَوِيُّ', transliteration: 'AL-QAWIYY', meaning: 'The All-Strong', urduMeaning: 'نہایت طاقتور'),
  AsmaUlHusnaModel(number: 55, arabic: 'الْمَتِينُ', transliteration: 'AL-MATEEN', meaning: 'The Firm', urduMeaning: 'مضبوط'),
  AsmaUlHusnaModel(number: 56, arabic: 'الْوَلِيُّ', transliteration: 'AL-WALIYY', meaning: 'The Protecting Friend', urduMeaning: 'حمایت کرنے والا دوست'),
  AsmaUlHusnaModel(number: 57, arabic: 'الْحَمِيدُ', transliteration: 'AL-HAMEED', meaning: 'The Praiseworthy', urduMeaning: 'قابلِ حمد'),
  AsmaUlHusnaModel(number: 58, arabic: 'الْمُحْصِي', transliteration: 'AL-MUHSEE', meaning: 'The Counter', urduMeaning: 'شمار رکھنے والا'),
  AsmaUlHusnaModel(number: 59, arabic: 'الْمُبْدِئُ', transliteration: 'AL-MUBDI', meaning: 'The Originator', urduMeaning: 'ابتدا کرنے والا'),
  AsmaUlHusnaModel(number: 60, arabic: 'الْمُعِيدُ', transliteration: 'AL-MU‘EED', meaning: 'The Restorer', urduMeaning: 'دوبارہ پیدا کرنے والا'),
  AsmaUlHusnaModel(number: 61, arabic: 'الْمُحْيِي', transliteration: 'AL-MUHYI', meaning: 'The Giver of Life', urduMeaning: 'زندگی دینے والا'),
  AsmaUlHusnaModel(number: 62, arabic: 'الْمُمِيتُ', transliteration: 'AL-MUMEET', meaning: 'The Giver of Death', urduMeaning: 'موت دینے والا'),
  AsmaUlHusnaModel(number: 63, arabic: 'الْحَيُّ', transliteration: 'AL-HAYY', meaning: 'The Ever-Living', urduMeaning: 'ہمیشہ زندہ'),
  AsmaUlHusnaModel(number: 64, arabic: 'الْقَيُّومُ', transliteration: 'AL-QAYYOOM', meaning: 'The Self-Sustaining', urduMeaning: 'سب کو قائم رکھنے والا'),
  AsmaUlHusnaModel(number: 65, arabic: 'الْوَاجِدُ', transliteration: 'AL-WAAJID', meaning: 'The Finder', urduMeaning: 'سب کچھ پانے والا'),
  AsmaUlHusnaModel(number: 66, arabic: 'الْمَاجِدُ', transliteration: 'AL-MAAJID', meaning: 'The Noble', urduMeaning: 'بزرگی والا'),
  AsmaUlHusnaModel(number: 67, arabic: 'الْوَاحِدُ', transliteration: 'AL-WAAHID', meaning: 'The One', urduMeaning: 'ایک'),
  AsmaUlHusnaModel(number: 68, arabic: 'الْأَحَدُ', transliteration: 'AL-AHAD', meaning: 'The Unique One', urduMeaning: 'یکتا'),
  AsmaUlHusnaModel(number: 69, arabic: 'الصَّمَدُ', transliteration: 'AS-SAMAD', meaning: 'The Eternal Refuge', urduMeaning: 'بے نیاز'),
  AsmaUlHusnaModel(number: 70, arabic: 'الْقَادِرُ', transliteration: 'AL-QAADIR', meaning: 'The Capable', urduMeaning: 'قدرت والا'),
  AsmaUlHusnaModel(number: 71, arabic: 'الْمُقْتَدِرُ', transliteration: 'AL-MUQTADIR', meaning: 'The Omnipotent', urduMeaning: 'کامل قدرت والا'),
  AsmaUlHusnaModel(number: 72, arabic: 'الْمُقَدِّمُ', transliteration: 'AL-MUQADDIM', meaning: 'The Expediter', urduMeaning: 'آگے کرنے والا'),
  AsmaUlHusnaModel(number: 73, arabic: 'الْمُؤَخِّرُ', transliteration: 'AL-MU’AKHKHIR', meaning: 'The Delayer', urduMeaning: 'پیچھے کرنے والا'),
  AsmaUlHusnaModel(number: 74, arabic: 'الْأَوَّلُ', transliteration: 'AL-AWWAL', meaning: 'The First', urduMeaning: 'سب سے پہلے'),
  AsmaUlHusnaModel(number: 75, arabic: 'الْآخِرُ', transliteration: 'AL-AAKHIR', meaning: 'The Last', urduMeaning: 'سب سے آخر'),
  AsmaUlHusnaModel(number: 76, arabic: 'الظَّاهِرُ', transliteration: 'AZ-ZAAHIR', meaning: 'The Manifest', urduMeaning: 'ظاہر'),
  AsmaUlHusnaModel(number: 77, arabic: 'الْبَاطِنُ', transliteration: 'AL-BAATIN', meaning: 'The Hidden', urduMeaning: 'پوشیدہ'),
  AsmaUlHusnaModel(number: 78, arabic: 'الْوَالِي', transliteration: 'AL-WAALI', meaning: 'The Governor', urduMeaning: 'اختیار رکھنے والا'),
  AsmaUlHusnaModel(number: 79, arabic: 'الْمُتَعَالِي', transliteration: 'AL-MUTA‘AALI', meaning: 'The Most Exalted', urduMeaning: 'بہت بلند'),
  AsmaUlHusnaModel(number: 80, arabic: 'الْبَرُّ', transliteration: 'AL-BARR', meaning: 'The Source of Goodness', urduMeaning: 'نیکی اور احسان کرنے والا'),
  AsmaUlHusnaModel(number: 81, arabic: 'التَّوَّابُ', transliteration: 'AT-TAWWAAB', meaning: 'The Acceptor of Repentance', urduMeaning: 'توبہ قبول کرنے والا'),
  AsmaUlHusnaModel(number: 82, arabic: 'الْمُنْتَقِمُ', transliteration: 'AL-MUNTAQIM', meaning: 'The Just Requiter', urduMeaning: 'بدلہ لینے والا'),
  AsmaUlHusnaModel(number: 83, arabic: 'الْعَفُوُّ', transliteration: 'AL-‘AFUWW', meaning: 'The Pardoner', urduMeaning: 'معاف کرنے والا'),
  AsmaUlHusnaModel(number: 84, arabic: 'الرَّؤُوفُ', transliteration: 'AR-RA’OOF', meaning: 'The Most Kind', urduMeaning: 'نہایت شفقت والا'),
  AsmaUlHusnaModel(number: 85, arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'MAALIK-UL-MULK', meaning: 'Owner of All Sovereignty', urduMeaning: 'تمام بادشاہی کا مالک'),
  AsmaUlHusnaModel(number: 86, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', transliteration: 'DHUL-JALAALI WAL-IKRAAM', meaning: 'Lord of Majesty and Honour', urduMeaning: 'جلال اور اکرام والا'),
  AsmaUlHusnaModel(number: 87, arabic: 'الْمُقْسِطُ', transliteration: 'AL-MUQSIT', meaning: 'The Equitable', urduMeaning: 'انصاف قائم کرنے والا'),
  AsmaUlHusnaModel(number: 88, arabic: 'الْجَامِعُ', transliteration: 'AL-JAAMI‘', meaning: 'The Gatherer', urduMeaning: 'جمع کرنے والا'),
  AsmaUlHusnaModel(number: 89, arabic: 'الْغَنِيُّ', transliteration: 'AL-GHANIYY', meaning: 'The Self-Sufficient', urduMeaning: 'بے نیاز'),
  AsmaUlHusnaModel(number: 90, arabic: 'الْمُغْنِي', transliteration: 'AL-MUGHNI', meaning: 'The Enricher', urduMeaning: 'بے نیاز کرنے والا'),
  AsmaUlHusnaModel(number: 91, arabic: 'الْمَانِعُ', transliteration: 'AL-MAANI‘', meaning: 'The Preventer', urduMeaning: 'روکنے والا'),
  AsmaUlHusnaModel(number: 92, arabic: 'الضَّارُ', transliteration: 'AD-DAARR', meaning: 'The One who permits adversity', urduMeaning: 'تکلیف پہنچنے کا اختیار رکھنے والا'),
  AsmaUlHusnaModel(number: 93, arabic: 'النَّافِعُ', transliteration: 'AN-NAAFI‘', meaning: 'The Benefactor', urduMeaning: 'نفع دینے والا'),
  AsmaUlHusnaModel(number: 94, arabic: 'النُّورُ', transliteration: 'AN-NOOR', meaning: 'The Light', urduMeaning: 'نور'),
  AsmaUlHusnaModel(number: 95, arabic: 'الْهَادِي', transliteration: 'AL-HAADI', meaning: 'The Guide', urduMeaning: 'ہدایت دینے والا'),
  AsmaUlHusnaModel(number: 96, arabic: 'الْبَدِيعُ', transliteration: 'AL-BADEE‘', meaning: 'The Incomparable Originator', urduMeaning: 'بے مثال پیدا کرنے والا'),
  AsmaUlHusnaModel(number: 97, arabic: 'الْبَاقِي', transliteration: 'AL-BAAQI', meaning: 'The Everlasting', urduMeaning: 'ہمیشہ باقی'),
  AsmaUlHusnaModel(number: 98, arabic: 'الْوَارِثُ', transliteration: 'AL-WAARITH', meaning: 'The Inheritor', urduMeaning: 'سب کا وارث'),
  AsmaUlHusnaModel(number: 99, arabic: 'الرَّشِيدُ', transliteration: 'AR-RASHEED', meaning: 'The Guide to the Right Way', urduMeaning: 'درست راہ دکھانے والا'),
];
