// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQFyubnBsPGTlIv51uqDSptK3wlq2M15Y',
    appId: '1:512308725569:web:5fe5f543fef52f8aedc3c0',
    messagingSenderId: '512308725569',
    projectId: 'seeker-1a492',
    authDomain: 'seeker-1a492.firebaseapp.com',
    storageBucket: 'seeker-1a492.firebasestorage.app',
    measurementId: 'G-WHEY2YRT9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyeZau-cvSuzuqppl9HWca9F5ph0PIPeU',
    appId: '1:512308725569:android:7f92e82c74256d35edc3c0',
    messagingSenderId: '512308725569',
    projectId: 'seeker-1a492',
    storageBucket: 'seeker-1a492.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwXStTfUoNmLOndbu0fiS3YIZrtS4_mH0',
    appId: '1:512308725569:ios:24c69f581218a282edc3c0',
    messagingSenderId: '512308725569',
    projectId: 'seeker-1a492',
    storageBucket: 'seeker-1a492.firebasestorage.app',
    iosBundleId: 'com.seeker.guidance',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwXStTfUoNmLOndbu0fiS3YIZrtS4_mH0',
    appId: '1:512308725569:ios:aa0cb28acae89435edc3c0',
    messagingSenderId: '512308725569',
    projectId: 'seeker-1a492',
    storageBucket: 'seeker-1a492.firebasestorage.app',
    iosBundleId: 'com.example.spiritualGuidance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQFyubnBsPGTlIv51uqDSptK3wlq2M15Y',
    appId: '1:512308725569:web:4702eef6aae95644edc3c0',
    messagingSenderId: '512308725569',
    projectId: 'seeker-1a492',
    authDomain: 'seeker-1a492.firebaseapp.com',
    storageBucket: 'seeker-1a492.firebasestorage.app',
    measurementId: 'G-KQM45L4ZBM',
  );
}
